name: Update Artist Data

on:
  schedule:
    # Run every 12 hours at 00:00 and 12:00 UTC
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    paths:
      - 'artists.json'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run automation script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python update_data.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/cache.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔥 Auto-update artist data [$(date +'%Y-%m-%d %H:%M UTC')]" && git push)
